### ISSUE TITLE
Add support for centered text fields

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui-react-components#14]
They are supposed to be working on ui-css, so it's just a matter of adding the option.

@moriaam @guyb7  @danevron

**Comment by danevron** [comment]
This is what I needed to do:

```
    <div className="cui__field is-centered">
       <label className="cui__field__label">
           Personal Number
       </label>
       <input className="cui__field__input" />
     </div>
```

I guess we need to expose a centered prop, something like: `<Field centered />` that will add the relevant css class.

WDYT @joaomilho?

**Comment by joaomilho** [comment]
That's precisely what we have to do :D

**Comment by xaviervia** [comment]
Isn't this already supported? https://github.com/klarna/ui-react-components/blob/master/components/Field.jsx#L44

**Comment by danevron** [comment]
If it is, My React knowledge is not enough to understand how to use it.
Can you give an example as   `<Field centered />` doesn't work for me.

**Comment by xaviervia** [comment]
I just tried and it works on `0.8.3` . Are you sure you are using the latest?

<img width="612" alt="screen shot 2016-05-09 at 16 42 16" src="https://cloud.githubusercontent.com/assets/381614/15116793/03b3aa32-1605-11e6-83b5-d1dab936d9b0.png">

**Comment by zenona** [comment]
For centered fields like this, would it be possible to have the cursor show at the beginning of the placeholder (at the left of 'E')? Found this as an example: http://making.fiftythree.com/fluid-text-inputs/ (ignore the magnifying lens and close icons)

![input-field](https://cloud.githubusercontent.com/assets/1679594/15117377/9218ede4-1607-11e6-9cb2-75503eb8d18c.gif)

**Comment by xaviervia** [comment]
My gut reaction is that it's super hard to do that. Since we would need to align the input field with the label and then move the input field, which is known to cause problems in several browsers. But I agree this looks ugly. I'll think about it.

**Comment by danevron** [comment]
It's an outdated version issue.
I'm closing this one.

Sorry for the trouble.
