### ISSUE TITLE
Paragraph color/design

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui-react-components#17]
If one tries to get the `secondary` paragraph it doesn't work, since it sets the color to `black` by default, and the secondary basically sets it to gray.

**Comment by xaviervia** [comment]
I thought this was fixed. I just ran into this one. Will fix now.

**Comment by xaviervia** [comment]
Ok I'm confused. In the showroom it can clearly be seen that it is working. But when I use it in the prototype, it sets it to black.

<img width="620" alt="screen shot 2016-05-20 at 14 12 22" src="https://cloud.githubusercontent.com/assets/381614/15427381/012c4d3a-1e95-11e6-8fad-efedf33a1ff9.png">

**Comment by xaviervia** [comment]
It seems to be working. I'm closing this one.
