### ISSUE TITLE
normalize.css should be used

### ISSUE THREAD

**Issue by JoakimLofgren** [klarna/ui-react-components#29]
To ensure that all browsers look the same (or as close as possible) I think it should be set as a devDependency and a peerDependency.

**Comment by xaviervia** [comment]
So far we are shying away from using normalization in the consumer apps.
Consumers might have their own normalizing stylesheets. But we should
certainly do it I'm the showroom.

**Comment by JoakimLofgren** [comment]
Doesn't that imply higher risk of something looking wrong because the normalization is not the same ?
And then they look at the examples and it looks correct ?

**Comment by joaomilho** [comment]
I'm on it.

**Comment by joaomilho** [comment]
#32

**Comment by xaviervia** [comment]
Merged long ago =)
