### ISSUE TITLE
Switches as input checkbox?

### ISSUE THREAD

**Issue by JoakimLofgren** [klarna/ui-react-components#34]
Wouldn't there be a lot less logic needed if we used a real checkbox which is `display:none` with a label attached to it? So when you click the label it changes the state of the checkbox without any onClick handlers?

Or was there a reason why you didn't use a checkbox underneath?

https://github.com/klarna/ui-react-components/blob/master/components/Switch.jsx#L70

**Comment by matthiasfeist** [comment]
As far as I know I did this for the menu component. This uses radiobuttons. So I guess it should be possible :)

**Comment by joaomilho** [comment]
I would say this should even be a general principle.

**Comment by joaomilho** [comment]
Although this is mainly a css-components issue, I'll keep it around, since there's a growing consensus we should monorepo (new verb, "to monorep") it.

**Comment by xaviervia** [comment]
We are still lacking in accessibility in general. We should revisit components one by one to make them more semantic and adding ARIA stuff to them.

**Comment by joaomilho** [comment]
I guess one thing to be aware when implementing this is how it looks like when the user does tab navigation.

**Comment by xaviervia** [comment]
Done in the new repo (and tab navigation works just fine =) )
