### ISSUE TITLE
Unify Input and Field components?

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui-react-components#37]
This is since we haven't actually deprecated Field thus far, and it seems that they are going to remain in use for a while. We could unify them and put `Field` behind a flag, since they have exactly the same API otherwise except for the `giant` size.

**Comment by joaomilho** [comment]
I think it's a good idea as long as we can truly not load all the selectors. Our builds are already getting huge.

**Comment by xaviervia** [comment]
Yeah, that's a good point. We should probably decorate the vanilla components with styles in HOC instead of the current approach, that should make the testing simpler.

**Comment by joaomilho** [comment]
Yeah, let's do it.

**Comment by xaviervia** [comment]
We are actually moving in the opposite direction right now. Let's skip this for now.
