### ISSUE TITLE
More colors for text components

### ISSUE THREAD

**Issue by JoakimLofgren** [klarna/ui-react-components#43]
For instance, if you wanted to do a error page, you might want red/error headers and paragraphs

**Comment by xaviervia** [comment]
I think we can use the same coloring that we do in the `cui__illustrations`: http://klarna.github.io/ui-css-components/#Illustration

That would be:

- Black (already there)
- Blue (already there for titles)
- Error
- Success
- Warning
- Gray (already there for paragraph [secondary])
- Inverse (white) (already there for some text)

**Comment by xaviervia** [comment]
Aaand done in the new repo https://github.com/klarna/ui/commit/841490e38644ea432c51761383ad35b0687f2b27
