### ISSUE TITLE
Subcomponents: export vs attribute

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui-react-components#50]
Currently we have 2 approaches for subcomponents.

#### Attribute

On Dialog & ContextMenu we use an attribute approach, so we export only `Dialog` and `Icon`, `Content`... are attributes of this exported function. The consumption is:

```js
import Dialog from '.../Dialog'
```
```html
<Dialog...>
  <Dialog.Icon ...>
  <Dialog.Content>
    ...
  </Dialog.Content>
</Dialog>
```

#### Export

On `Preview` we export the subcomponents (`PreviewTitle`, `PreviewLink` ...), so the usage is:

```js
import Preview, { PreviewTitle, PreviewLink } from '.../Preview'
```

```html
<Preview>
  <PreviewTitle>...<PreviewTitle>
  <PreviewLink>...<PreviewLink>
</Preview>
```

##### pros
- Clean import
- Seems to me `Foo.Bar` makes it absolutely clear that `Bar` should be used in the context of `Foo`, while `FooBar` although clear is not _that_ clear.

##### cons
- I'm unsure it's actually a good practice to put things as attrs of a function, but I can't see where it hurts.
- We _have_ to set `displayName`, either manually or by some webpack magic. (I don't think it's a big deal)

##### pros
- Seems to be the "correct" way;
- Explicit import
- Could split into multiple files, therefore reducing load if people don't need a specific subcomponent. I don't think this is so relevant, since it would make imports worse.

##### cons
- Polluted import

## Finally
Since the majority of components are using the attribute way, the shortest amount of work would be to change the ones that are currently using export (also in the projects that consume 'em). This may be a decisive factor if we're 50/50 on this one.

**Comment by JoakimLofgren** [comment]
You messed up the cons section. It needs some more blank lines?

I prefer export. And you can also do `import { X as Y }` so you can easily avoid collisions.

**Comment by JoakimLofgren** [comment]
Nice I could edit your message :smile:

**Comment by ChristerGustavsson** [comment]
I suppose you could do the wildcard import with exports:

```js
import * as Preview from '.../Preview'
```

```html
<Preview.default>
  <Preview.PreviewTitle>...<Preview.PreviewTitle>
  <Preview.PreviewLink>...<Preview.PreviewLink>
</Preview.default>
```

But it looks pretty ugly to be honest.

I think I would prefer attributes because it seems cleaner. But what's that about `displayName`? I didn't notice that earlier when I was playing around with the `Dialog` component.

**Comment by Nevon** [comment]
To me, the export approach seems the cleaner one. It will also help with tree shaking, as in the attribute approach, there is no way to know at build time whether or not the subcomponents need to be included or not.

**Comment by joaomilho** [comment]
I'll create a sample project and validate that tree shaking will really do what is expected. If that's the case I suppose that's the way to go.

**Comment by xaviervia** [comment]
Makes me a little sad though. In my view its undoubtedly uglier with the exports. But it kind of feel like the proper way, since the different subcomponents are properties of the module, not of another component.

Maybe we could still export them with unprefixed names, such as `Main`, `Title` and `Link` in @ChristerGustavsson 's suggestion? We can always force the namespace by importing like:

```javascript
import * as Preview from '@klarna/ui-react-components/components/Preview'
```

```html
<Preview.Main>
  <Preview.Title>...<Preview.Title>
  <Preview.Link>...<Preview.Link>
</Preview.Main>
```

**Comment by joaomilho** [comment]
Seems to be the best of both worlds. Keeps imports minimal and yet allows tree shaking.

**Comment by joaomilho** [comment]
So after this whole discussion I assume the decision is to go for the exports approach. I'll close this one and add issues for refactoring the relevant components.

**Comment by joaomilho** [comment]
Action item on #53
