### ISSUE TITLE
Change Dialog & ContextMenu to follow the exports convention

### ISSUE THREAD

**Issue by joaomilho** [klarna/ui-react-components#53]
According to #50 we must refactor Dialog & ContextMenu to follow the exports convention, so their usage should be

```js
import * as Dialog from '.../Dialog'
```
```html
<Dialog.Main...>
  <Dialog.Icon ...>
  <Dialog.Content>
    ...
  </Dialog.Content>
</Dialog.Main>
```
instead of the current

```js
import Dialog from '.../Dialog'
```
```html
<Dialog...>
  <Dialog.Icon ...>
  <Dialog.Content>
    ...
  </Dialog.Content>
</Dialog>
```

As discussed, the main advantages of this approach are to a) comply with module standards and b) the possibility of tree shaking and smaller builds.

**Comment by xaviervia** [comment]
Done in the new repo
