### ISSUE TITLE
Start interaction onTouchStart in mobile

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui-react-components#7]
Why? 

*The default interaction model is too slow*

It feels slow, it's annoying for the user, it's distracting.

**Comment by joaomilho** [comment]
So if we use onTourchStart it removes the 300s of clicks? What about `focus` for instance?

**Comment by xaviervia** [comment]
Yes. It's problematic, we probably need to add a ghost click protector (is there a public explanation of that issue @Nevon ? ). But we can probably skip `onTouchStart` for inputs for the time being, at least adding it to buttons which are safer (since they don't pop up keyboards) since it's pretty annoying to have the buttons so slow.

**Comment by joaomilho** [comment]
I feel if we're dealing with the 300ms thing I see no reason not to solve it in the components level.

**Comment by xaviervia** [comment]
True that. Let's do it then, but I guess after the showroom.

**Comment by xaviervia** [comment]
Moved to https://github.com/klarna/ui/issues/35
